#날짜: 2023/06/16
#이름: 조유빈
#내용: 3. 데이터 베이스 관리

#실습 3-1
CREATE DATABASE `TestDB`;
CREATE USER 'Tester'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILLEGES ON TESTDB. * TO 'tester'@'%';
FLUSH PRIVILEGES;

#실습 3-2
ALTER USER 'Tester'@'%' IDENTIFIED BY '12345';
DROP USER 'Tester' @'%';
FLUSH PRIVILEGES;